### ISSUE TITLE
everything opens up fine but commands dont work?

### ISSUE THREAD

**Issue by cctestiomio** [polyllc/discord-gameboy#2]
i launch with node gameboy.js and it shows nothing in command window

i type "gameboy help" and the bot does message out the info in discord

i type "load rom pokered.gb" and pokered.gb is in /games/ but nothing happens

i type "load rom" and it says "@name, upload a rom too" and in command prompt it shows Collection(0) [Map] {}

https://i.imgur.com/D9pWKCg.png

im using ur 1.02 release so im sure all the packages / installation is correct.

**Comment by polyllc** [comment]
you'll need to upload the file alongside the message `load rom` in discord. The next release will support roms in the games folder, but right now, the games folder is used for the bot. I did this initially so people can't play games they don't own, but I guess if you have the bot running personally, there is no point in that restriction. I am updating the bot soon, right now, hybrid mode is the one that works the best.
