### ISSUE TITLE
doesnt do anything

### ISSUE THREAD

**Issue by arceuss** [polyllc/discord-gameboy#3]
i installed everything and ran it but loading a rom has no response
nothing in console either

**Comment by arceuss** [comment]
is it a issue with windows or anything

**Comment by polyllc** [comment]
First off, are you using the node command or are you using pm2. You'll need to attach to the process with pm2 with `pm2 attach 0`. Check if your bot is online and check if the bot is correctly working with the help command, `gameboy help`. Also check if the rom is valid.

**Comment by arceuss** [comment]
im using node and gameboy help does work and the rom im trying to use is pokemon crystal clear

**Comment by polyllc** [comment]
Make sure you're uploading the rom with the message `load rom` in discord. A common confusion is that people put the rom in the roms folder and think it'll autoboot, but this is actually for the bot so it can store the rom _temporarily_.

**Comment by arceuss** [comment]
i am doing that though

**Comment by polyllc** [comment]
are you sure that the bot is an admin? there isn't any permission checking yet, and it might be trying to do something that it doesn't have permission for. Also, you might have to wait a bit (~10 seconds) for it to download and setup the emulator. Also check the rom in an emulator. The `load rom` command is case sensitive. Also make sure the rom is a `.gb` or `.gbc` and not a zip.

**Comment by arceuss** [comment]
the bot has all perms and its a gbc file and it runs fine in a emulator

**Comment by polyllc** [comment]
Did you do a manual install or did you use the pre made package?

**Comment by arceuss** [comment]
pre made

**Comment by polyllc** [comment]
try installing the packages (except the gameboy package) manually. That would be `request` and `discord.js`, the packages are out of date at this point as I have not updated the bot

**Comment by polyllc** [comment]
closed due to inactivity

**Comment by WinUser-Generic** [comment]
Here facing exactly the same after need to adivinate release needed specific nodejs 14.x to get running, could be nice if get a answer

**Comment by polyllc** [comment]
> Here facing exactly the same after need to adivinate release needed specific nodejs 14.x to get running, could be nice if get a answer ![image](https://private-user-images.githubusercontent.com/159548162/339168012-854708b0-ff00-4b9a-8eea-fdc5486cda46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzk4MDYsIm5iZiI6MTcxODIzOTUwNiwicGF0aCI6Ii8xNTk1NDgxNjIvMzM5MTY4MDEyLTg1NDcwOGIwLWZmMDAtNGI5YS04ZWVhLWZkYzU0ODZjZGE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzc5ODg4N2VmNzBkYWNmNjBiMmU3YTRmZGNlY2E2NWZlNWY5NmU5OGExNDAwNmVmOWQ0YzM4NWU5MmU3NGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mYOrpcUyBqHt5cy4MwaUKoBe1Jg-JHJWK13OofApr0I)
> 
> same if i run with powershell or cmd
> 
> ![image](https://private-user-images.githubusercontent.com/159548162/339167673-7ca898de-68a1-44ff-aed3-a84cb8e1b8e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzk4MDYsIm5iZiI6MTcxODIzOTUwNiwicGF0aCI6Ii8xNTk1NDgxNjIvMzM5MTY3NjczLTdjYTg5OGRlLTY4YTEtNDRmZi1hZWQzLWE4NGNiOGUxYjhlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWZkNzdjNWU1YmMxOWU4YjMyN2I0Y2U1YjU4YTMyNDhjNDQwMTc0OTFlMWFhYmViOGFjYThjYzk5MTA2ZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.scFEOqap2feItNNSQa1pKXPAAQbj74vi9qVzQfCvh84)
> 
> Even using pm2 get the same result the bot does nothing when write load rom + attached rom or ``gameboy help´´ had admin rights

I just installed the bot, and barring some dependencies, it seems to work fine. I think what might be happening is that your discord bot doesn't have the message content intent on in discord, which you can enable 
![image](https://github.com/polyllc/discord-gameboy/assets/46696863/b3ef8235-dd18-4be6-9d1a-95110441367d)
here. hopefully this helps.

**Comment by WinUser-Generic** [comment]
> > Here facing exactly the same after need to adivinate release needed specific nodejs 14.x to get running, could be nice if get a answer ![image](https://private-user-images.githubusercontent.com/159548162/339168012-854708b0-ff00-4b9a-8eea-fdc5486cda46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzk4MDYsIm5iZiI6MTcxODIzOTUwNiwicGF0aCI6Ii8xNTk1NDgxNjIvMzM5MTY4MDEyLTg1NDcwOGIwLWZmMDAtNGI5YS04ZWVhLWZkYzU0ODZjZGE0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzc5ODg4N2VmNzBkYWNmNjBiMmU3YTRmZGNlY2E2NWZlNWY5NmU5OGExNDAwNmVmOWQ0YzM4NWU5MmU3NGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mYOrpcUyBqHt5cy4MwaUKoBe1Jg-JHJWK13OofApr0I)
> > same if i run with powershell or cmd
> > ![image](https://private-user-images.githubusercontent.com/159548162/339167673-7ca898de-68a1-44ff-aed3-a84cb8e1b8e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMzk4MDYsIm5iZiI6MTcxODIzOTUwNiwicGF0aCI6Ii8xNTk1NDgxNjIvMzM5MTY3NjczLTdjYTg5OGRlLTY4YTEtNDRmZi1hZWQzLWE4NGNiOGUxYjhlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwMDQ1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWZkNzdjNWU1YmMxOWU4YjMyN2I0Y2U1YjU4YTMyNDhjNDQwMTc0OTFlMWFhYmViOGFjYThjYzk5MTA2ZWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.scFEOqap2feItNNSQa1pKXPAAQbj74vi9qVzQfCvh84)
> > Even using pm2 get the same result the bot does nothing when write load rom + attached rom or ``gameboy help´´ had admin rights
> 
> I just installed the bot, and barring some dependencies, it seems to work fine. I think what might be happening is that your discord bot doesn't have the message content intent on in discord, which you can enable ![image](https://private-user-images.githubusercontent.com/46696863/339172112-b3ef8235-dd18-4be6-9d1a-95110441367d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNDM2OTUsIm5iZiI6MTcxODI0MzM5NSwicGF0aCI6Ii80NjY5Njg2My8zMzkxNzIxMTItYjNlZjgyMzUtZGQxOC00YmU2LTlkMWEtOTUxMTA0NDEzNjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDAxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzY3MGY0YjY0ZjA2NDNlOWUwZDEyYjgwNjM4MGYzM2UwODJkOTc0NTNlOWJjODZlMTNhM2U1MTc0NDU1NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gxjCCDTWF8ILi0JgMFGGBWP69sFPmTEurQsSmMYq9o) here. hopefully this helps.

Really thanks, that option was!
